apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: michael
  namespace: {{ .Values.application.name }}
spec:
  clusterResourceWhitelist:
  - group: ""
    kind: ""
  destinations:
  - name: '*'
    namespace: {{ .Values.application.name }}
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - '*'