apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.application.name }}-binding
  namespace: {{ .Values.application.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: {{ .Values.application.name }}-enroller
  namespace: customer-argocd-controlplane